-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
require("scripts.insert_path")
require("scripts.lazygit_custom")
require("scripts.delete_shadas")
require("scripts.grep_in_neotree_dir")
require("functions.toggle_quickfix")
require("functions.yank_buffer_rel_path")
require("python.search_python_imports")
require("python.search_python_usage")
vim.lsp.set_log_level("info")
